### ISSUE TITLE
Why parametric init still has poorer performance than non-parametric one?

### ISSUE THREAD

**Issue by lakest** [matsui528/nanopq#39]
Hi! I like your code a lot! But there is one question: Why is that when I change the parameters in the `test_parametric_init` to `N, D, M, Ks = 100, 12, 4, 20`, the test will fail?

Do you have any idea? I thought the rotation matrix would work with different `M`s.

**Comment by matsui528** [comment]
You seem right. Changing M causes an error. Here's what I can tell you now:

- The specially-computed initial values are determined by setting `parametric_init=True`, while the random initial values are assigned if `parametric_init=False`. It happens that the former could be worse than the latter in some cases.
- Our implementation is a direct translation of the original MATLAB code anyway.

Closing the issue now, but please let me know if you find a way to solve this issue.
