### ISSUE TITLE
OPQ prints about Reconstruction error even with verbose=False

### ISSUE THREAD

**Issue by thomasahle** [matsui528/nanopq#8]
The Optimized PQ class takes a `verbose` flag, and this is passed to the inner PQ class.
However, it would make sense if OPQ also obeyed this flag in its `fit` method, which outputs lots of things about "Reconstruction error".

**Comment by matsui528** [comment]
Make sense. I've updated it (v0.1.9), so can you install the library again? https://github.com/matsui528/nanopq/pull/9

**Comment by thomasahle** [comment]
Thanks! Perfect.
